### PR TITLE
Add support for custom delegated targets

### LINKED ISSUE #517: Task: add support for custom delegated Target roles at `POST /api/v1/bootstrap`
### What is the task about?

We want to add support for custom delegated Target roles.
To achieve this we should support a new optional attribute called `custom_targets` inside `POST /api/v1/bootstrap`.
It should be inside settings and contain:
```
{
  "settings": {
      "custom_targets" {
           "<rolename>": {
               "expiration": <value>,
               "path_prefixes": <value>
           },
           ...
       }
     ...
  }
}
```

where `expiration` should be an integer and `path_prefixes` will be a list of strings.

### Parent feature

[Feature: Create/Remove custom delegate Target Roles](https://github.com/repository-service-tuf/repository-service-tuf/issues/354)

### References

- Worker: https://github.com/repository-service-tuf/repository-service-tuf-worker/issues/438

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by MVrachev**
****NOTE:** This pr should be merged after #554 as it's using the changes from that pr.**

Fixes #517  

# Description

Add support for custom delegated targets which could be used by PyPI and other of our users.
This will allow for greater flexibility and we could support special use cases for bigger users.

Note: it's related to pr https://github.com/repository-service-tuf/repository-service-tuf-worker/pull/457. When testing use both this and the worker pr.

# Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)

# Additional requirements
- [x] Tests have been added for the bug fix or new feature
- [x] Docs have been added for the bug fix or new feature

# Code of Conduct
By submitting this PR, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.rst).

- [ ] I agree to follow this project's Code of Conduct

### CODE REVIEW

**Comment by MVrachev** [comment]
I had a problem that in the documentation `PUT /api/v1/config` the example looks strange:
Untitled

I tried fixing it by using the new `ConfigDict` of pydantic like this:
```
with open("tests/data_examples/config/update_settings.json") as f:
    content = f.read()
example_settings = json.loads(content)


class PutPayload(BaseModel):
    model_config = ConfigDict(json_schema_extra={"example": example_settings})
    settings: Settings
```

but it seems it's not helping.

**Comment by MVrachev** [comment]
> I had a problem that in the documentation `PUT /api/v1/config` the example looks strange: image
> 
> I tried fixing it by using the new `ConfigDict` of pydantic like this:
> 
> ```
> with open("tests/data_examples/config/update_settings.json") as f:
>     content = f.read()
> example_settings = json.loads(content)
> 
> 
> class PutPayload(BaseModel):
>     model_config = ConfigDict(json_schema_extra={"example": example_settings})
>     settings: Settings
> ```
> 
> but it seems it's not helping.

This problem was solved with my latest commit.

**Comment by MVrachev** [comment]
Ready to review this @kairoaraujo.

**Comment by MVrachev** [comment]
In one of my latest commits https://github.com/repository-service-tuf/repository-service-tuf-api/pull/542/commits/f3654eb2ac72d10a3b430dfc27e4207ca2a2d5df I think I fix
https://github.com/repository-service-tuf/repository-service-tuf-api/issues/532

**Comment by MVrachev** [comment]
Ready to review after rebased on top of the latest changes changing the bootstrap payload.

**Review by kairoaraujo — APPROVED** [review]

**Pull request merged**
